
class Produto1 {
  String id;
  String codigo;
  String descricao;
  String precoUn;
  String ventrada;
  int quantidade;
  String tipo;
  String unidade;
  String unidadeTributavel;
  String data;
  String loja;
  double subtotal;
  String vendedor_id;
  String cst;
  String cfop;
  String baseICMS;
  String icms;
  String aliquotaICMS;
  String cest;
  String cean;
  String ceanTrib;
  String qTrib;
  String vUnTrib;
  int item;
  String bcICMS;
  String bcICMSST;
  String pmvast;
  String predBCST;
  String vBCST;
  String picmsST;
  String vicmsST;
  String predBC;
  String pDif;
  String vicmsDif;
  String vicms;
  String pCredSN;
  String vCredICMSSN;
  String cstPIS;
  String vBCPIS;
  String pPIS;
  String vPIS;
  String cstCOFINS;
  String vBCCOFINS;
  String pCOFINS;
  String vCOFINS;
  String aFederalN;
  String aFederalI;
  String aEstadual;
  String aMunicipal;

  Produto1({
    required this.id,
    required this.codigo,
    required this.descricao,
    required this.precoUn,
    required this.ventrada,
    required this.quantidade,
    required this.tipo,
    required this.unidade,
    required this.unidadeTributavel,
    required this.data,
    required this.loja,
    required this.subtotal,
    required this.vendedor_id,
    required this.cst,
    required this.cfop,
    required this.baseICMS,
    required this.icms,
    required this.aliquotaICMS,
    required this.cest,
    required this.cean,
    required this.ceanTrib,
    required this.qTrib,
    required this.vUnTrib,
    required this.item,
    required this.bcICMS,
    required this.bcICMSST,
    required this.pmvast,
    required this.predBCST,
    required this.vBCST,
    required this.picmsST,
    required this.vicmsST,
    required this.predBC,
    required this.pDif,
    required this.vicmsDif,
    required this.vicms,
    required this.pCredSN,
    required this.vCredICMSSN,
    required this.cstPIS,
    required this.vBCPIS,
    required this.pPIS,
    required this.vPIS,
    required this.cstCOFINS,
    required this.vBCCOFINS,
    required this.pCOFINS,
    required this.vCOFINS,
    required this.aFederalN,
    required this.aFederalI,
    required this.aEstadual,
    required this.aMunicipal,
  });
}